"""
services/digest_service.py  [Phase 4]

Orchestrates topic fetching + LLM call + HTML wrapping.
Returns a complete, self-contained HTML document.
"""

import logging
from datetime import date

from llm.client import LLMClient
from services.topic_service import get_topics

logger = logging.getLogger(__name__)


class DigestService:

    def __init__(self, llm_client: LLMClient):
        self.llm = llm_client

    def generate(self) -> str:
        """
        Full pipeline:
          1. Load topics
          2. Call LLM
          3. Wrap in a complete HTML document
        Returns the HTML string.
        """
        topics = get_topics()
        logger.info(f"Generating digest for {len(topics)} topic(s)...")

        body_html = self.llm.generate(topics)

        today = date.today().strftime("%B %d, %Y")
        title = f"Daily Learning Digest — {today}"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
</head>
<body>
  <h1>{title}</h1>
  <p><em>{len(topics)} topic(s) • Generated by Bitty Bettr</em></p>
  <hr>
  {body_html}
</body>
</html>"""

        logger.info("Digest HTML assembled.")
        return html
