"""
services/digest_service.py  [Phase 4]

Orchestrates topic fetching + LLM call + HTML wrapping.
Returns a complete, self-contained HTML document.
"""

import logging
from datetime import date

from llm.client import LLMClient
from services.topic_service import get_topics, mark_topics_processed

logger = logging.getLogger(__name__)


class DigestService:

    def __init__(self, llm_client: LLMClient):
        self.llm = llm_client

    def generate(self, user_id: str) -> tuple[str, str]:
        """
        Full pipeline:
          1. Load topics
          2. Call LLM
          3. Wrap in a complete HTML document
          4. Mark topics as processed
        Returns a tuple of (HTML string, Title string).
        """
        topics = get_topics(user_id, limit=5)
        logger.info(f"Generating digest for {len(topics)} topic(s) for user {user_id}...")

        body_html = self.llm.generate(topics)
        
        # Mark as processed only if generation succeeded without raising exception
        mark_topics_processed(user_id, topics)

        today = date.today().strftime("%B %d, %Y")
        topics_str = ", ".join(topics).title()
        title = f"Digest: {topics_str[:40]}" + ("..." if len(topics_str)>40 else "") + f" ({today})"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
</head>
<body>
  <h1>{title}</h1>
  <p><em>{len(topics)} topic(s) • Generated by Bitty Bettr</em></p>
  <hr>
  {body_html}
</body>
</html>"""

        logger.info("Digest HTML assembled.")
        return html, title
